// <auto-generated />
using System;
using GameRev.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameRev.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410085321_TestMigration")]
    partial class TestMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GameRev.Models.Auth.UserSession", b =>
                {
                    b.Property<long>("Jtid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("jwt_token_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Jtid"));

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Jtid");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("GameRev.Models.Entities.Author", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("GameRev.Models.Entities.Platform", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("GameRev.Models.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<double>("Rating")
                        .HasColumnType("double")
                        .HasColumnName("score");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("review_date");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("VideogameId")
                        .HasColumnType("bigint")
                        .HasColumnName("videogame_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VideogameId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("GameRev.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("email");

                    b.Property<long?>("Jtid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastAccess")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_access_date");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("password");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("registration_date");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("Basic")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameRev.Models.Entities.Videogame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cover_image");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("Objectives")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("publication_date");

                    b.Property<bool>("Released")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("released");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Videogames");
                });

            modelBuilder.Entity("GameRev.Models.Entities.VideogamePlatform", b =>
                {
                    b.Property<long>("VideogameId")
                        .HasColumnType("bigint")
                        .HasColumnName("videogame_id");

                    b.Property<long>("PlatformId")
                        .HasColumnType("bigint")
                        .HasColumnName("platform_id");

                    b.HasKey("VideogameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("VideogamePlatforms");
                });

            modelBuilder.Entity("PlatformVideogame", b =>
                {
                    b.Property<long>("PlatformsId")
                        .HasColumnType("bigint");

                    b.Property<long>("VideogamesId")
                        .HasColumnType("bigint");

                    b.HasKey("PlatformsId", "VideogamesId");

                    b.HasIndex("VideogamesId");

                    b.ToTable("PlatformVideogame");
                });

            modelBuilder.Entity("GameRev.Models.Auth.UserSession", b =>
                {
                    b.HasOne("GameRev.Models.Entities.User", "User")
                        .WithOne("UserSession")
                        .HasForeignKey("GameRev.Models.Auth.UserSession", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameRev.Models.Entities.Review", b =>
                {
                    b.HasOne("GameRev.Models.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameRev.Models.Entities.Videogame", "Videogame")
                        .WithMany("Reviews")
                        .HasForeignKey("VideogameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("GameRev.Models.Entities.Videogame", b =>
                {
                    b.HasOne("GameRev.Models.Entities.Author", "Author")
                        .WithMany("Videogames")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("GameRev.Models.Entities.VideogamePlatform", b =>
                {
                    b.HasOne("GameRev.Models.Entities.Platform", "Platform")
                        .WithMany("VideogamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameRev.Models.Entities.Videogame", "Videogame")
                        .WithMany("VideogamePlatforms")
                        .HasForeignKey("VideogameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("PlatformVideogame", b =>
                {
                    b.HasOne("GameRev.Models.Entities.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameRev.Models.Entities.Videogame", null)
                        .WithMany()
                        .HasForeignKey("VideogamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameRev.Models.Entities.Author", b =>
                {
                    b.Navigation("Videogames");
                });

            modelBuilder.Entity("GameRev.Models.Entities.Platform", b =>
                {
                    b.Navigation("VideogamePlatforms");
                });

            modelBuilder.Entity("GameRev.Models.Entities.User", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("GameRev.Models.Entities.Videogame", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("VideogamePlatforms");
                });
#pragma warning restore 612, 618
        }
    }
}
